title: "SafePR"
email: aran.mohammad@imes.uni-hannover.de
description: >-
  Unified Approach for Safe Parallel Robots
github_username: aranmoha
remote_theme: pmarsceill/just-the-docs
color_scheme: "theme"
