function dxp_ds_3RRRreturn = dxp_ds_3RRR(qjj_rad, qjk_rad, qji_rad, xEE, psi_beta_rad, l_all, r_BasisPla_MobPla, contactpoint)
  dxp_dsT = [0 0 0;];
  t3 = psi_beta_rad(1) + qjj_rad(1);
  t4 = cos(t3);
  t5 = l_all(1);
  t7 = contactpoint(2);
  dxp_dsT(1,1) = t5 * t4 * t7;
  t8 = sin(t3);
  dxp_dsT(1,2) = t7 * t5 * t8;
  dxp_dsT(1,3) = 0.0e0;
  dxp_ds_3RRRreturn = dxp_dsT;
